"""add users and file ownership

Revision ID: 1b00f45a2698
Revises: dffaeac8f5e0
Create Date: 2026-10-05 22:55:59.248692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b00f45a2698'
down_revision: Union[str, Sequence[str], None] = 'dffaeac8f5e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('files', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_files_filename'), table_name='files')
    op.create_index(op.f('ix_files_owner_id'), 'files', ['owner_id'], unique=False)
    op.create_unique_constraint('uq_files_owner_filename', 'files', ['owner_id', 'filename'])
    op.create_foreign_key('files_owner_id_fkey', 'files', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('files_owner_id_fkey', 'files', type_='foreignkey')
    op.drop_constraint('uq_files_owner_filename', 'files', type_='unique')
    op.drop_index(op.f('ix_files_owner_id'), table_name='files')
    op.create_index(op.f('ix_files_filename'), 'files', ['filename'], unique=True)
    op.drop_column('files', 'owner_id')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
