"""add user storage quota

Revision ID: 66100af107ea
Revises: 1b00f45a2698
Create Date: 2026-10-05 23:23:34.826889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66100af107ea'
down_revision: Union[str, Sequence[str], None] = '1b00f45a2698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('quota_bytes', sa.BigInteger(), server_default='5368709120', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'quota_bytes')
    # ### end Alembic commands ###
