server_tokens off;

upstream api_upstream {
    server api:8000;
}

upstream silo_upstream {
    server silo:9000;
}

server {
    listen 80;
    server_name localhost;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name localhost;

    ssl_certificate     /etc/nginx/certs/localhost.crt;
    ssl_certificate_key /etc/nginx/certs/localhost.key;
    ssl_protocols       TLSv1.2 TLSv1.3;

    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header Referrer-Policy "no-referrer" always;
    # add_header Strict-Transport-Security "max-age=31536000" always;  # aktifkan hanya di domain production

    client_max_body_size 1m;

    location /cloud-storage/ {
        proxy_pass http://silo_upstream;
        proxy_set_header Host $http_host;
        proxy_set_header Authorization "";
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_hide_header Strict-Transport-Security;
        proxy_hide_header X-Xss-Protection;
        proxy_hide_header X-Content-Type-Options;
    }

    location / {
        proxy_pass http://api_upstream;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_request_buffering off;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }
}
